{"name": "test_ces_usdt_price_range", "status": "failed", "statusDetails": {"message": "AssertionError: Неожиданная цена для CES-USDT: 3.3626409315909. Ожидалось в диапазоне 0.0001-1\nassert 3.3626409315909 <= 1", "trace": "tests/special/test_pair_specific.py:54: in test_ces_usdt_price_range\n    assert 0.0001 <= latest_price <= 1, (\nE   AssertionError: Неожиданная цена для CES-USDT: 3.3626409315909. Ожидалось в диапазоне 0.0001-1\nE   assert 3.3626409315909 <= 1"}, "description": "Проверяет, что цена CES в USDT находится в разумном диапазоне", "start": 1758131983439, "stop": 1758131983864, "uuid": "c01d03bd-f0df-47e1-bca2-2a692d57c9b2", "historyId": "f4bb2b5a93e9bd6dcbe2e9f83cc5281e", "testCaseId": "f4bb2b5a93e9bd6dcbe2e9f83cc5281e", "fullName": "tests.special.test_pair_specific#test_ces_usdt_price_range", "labels": [{"name": "parentSuite", "value": "tests.special"}, {"name": "suite", "value": "test_pair_specific"}, {"name": "host", "value": "826d662bff36"}, {"name": "thread", "value": "2128-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.special.test_pair_specific"}], "titlePath": ["tests", "special", "test_pair_specific.py"]}